services:
  - type: web
    name: frontend-cantine
    runtime: node
    buildCommand: chmod +x frontend/render-build.sh && ./frontend/render-build.sh
    staticPublishPath: "./dist"
    startCommand: npx serve dist -l $PORT
    env: node
    envVars:
      - key: VITE_API_BASE_URL
        value: https://gestion-cantine-backend.onrender.com
      - key: PORT
        value: 10000
